export enum ActionType {
  PAY = 'PAY',
  PAYOUT = 'PAYOUT',
  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  GET_CUSTOMER = 'GET_CUSTOMER',
  SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD',
  PAYMENT_DETAILS = 'PAYMENT_DETAILS',
}
