export enum UrlPaths {
  Challenge = '/challenge',
  Login = '/auth/login',
  SignUp = '/auth/sign-up',
  Home = '/',
  Picks = '/picks',
  Profile = '/profile',
  ProfileAccountDeposit = '/profile/account-deposit',
  ProfileDetails = '/profile/details',
  ProfileSettings = '/profile/settings',
  ProfileWithdrawFunds = '/profile/withdraw-funds',
  ProfileReferral = '/profile/referral',
  Logout = '/logout',
  Contests = '/contests',
  Cart = '/cart',
  ProfileManagement = '/profile/management',
}
