/**
 * Adds seed data to your db
 *
 * @link https://www.prisma.io/docs/guides/database/seed-database
 */
import { ContestType, PrismaClient } from '@prisma/client';
import dayjs from 'dayjs';
import { appRouter } from '~/server/routers/_app';

const prisma = new PrismaClient();

const caller = appRouter.createCaller({} as any);

/**
 * 1. Create a joinable matchplay contest
 * 2. Create a joinable fantasy contest
 * 3. A contest already in play.
 */
async function main() {
  await prisma.contest.deleteMany();
  await prisma.user.deleteMany();
  await prisma.contestEntry.deleteMany();
  await caller.user.signUp({
    email: 'test@gmail.com',
    password: 'Password1!',
    confirmPassword: 'Password1!',
    username: 'testing',
    DOB: new Date(),
    phone: '12392342999',
    state: 'TX',
  });
  const user = await prisma.user.findFirst();
  await prisma.contest.upsert({
    create: {
      id: '2d500af0-9e18-47d7-80b0-fe51125497ae',
      name: 'Fantasy Contest',
      description: 'This is a match play contest',
      isActive: true,
      startDate: dayjs().subtract(1, 'h').toDate(),
      endDate: dayjs().add(1, 'day').toDate(),
      type: ContestType.FANTASY,
      bgImageUrl: 'https://picsum.photos/200',
      entryFee: 200,
      totalPrize: 1000,
      created_at: new Date(),
      updated_at: new Date(),
      ContestEntries: {
        create: {
          id: 'contest-id-entry',
          tokens: 1000,
          User: {
            connect: {
              id: user?.id,
            },
          },
        },
      },
    },
    update: {},
    where: {
      id: '2d500af0-9e18-47d7-80b0-fe51125497ae',
    },
  });
  const gamedate = dayjs().add(1, 'd');
  await prisma.offer.create({
    data: {
      gid: '57767',
      league: 'NCAAF',
      gamedate: gamedate.format('DD/MM/YYYY'),
      epoch: gamedate.unix(),
      start_utc: gamedate.toISOString(),
      end_utc: gamedate.add(2, 'h').toISOString(),
      inplay: false,
      status: 'InProgress',
      matchup: 'BAYLOR @ WVU',
      gametime: gamedate.format('HH:MM:SS'),
      home: {
        create: {
          id: 1544,
          name: 'West Virginia',
          code: 'WVU',
        },
      },
      away: {
        create: {
          id: 1430,
          name: 'Baylor',
          code: 'BAYLOR',
        },
      },
      markets: {
        createMany: {
          data: [
            {
              id: '57767-220-554186',
              type: 'PP',
              category: 'Receiving Yards',
              name: 'Monaray Baldwin',
              teamAbbrev: 'BAYLOR',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 64.5,
              over: -120,
              under: -120,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 554186,
              sel_id: 554186,
            },
            {
              id: '57767-215-539394',
              type: 'PP',
              category: 'Passing Yards',
              name: 'Blake Shapen',
              teamAbbrev: 'BAYLOR',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 225.5,
              over: -120,
              under: -120,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 539394,
              sel_id: 539394,
            },
            {
              id: '57767-220-558570',
              type: 'PP',
              category: 'Receiving Yards',
              name: 'Hal Presley',
              teamAbbrev: 'BAYLOR',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 38.5,
              over: -120,
              under: -120,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 558570,
              sel_id: 558570,
            },
            {
              id: '57767-215-534184',
              type: 'PP',
              category: 'Passing Yards',
              name: 'JT Daniels',
              teamAbbrev: 'WVU',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 239.5,
              over: -120,
              under: -120,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 534184,
              sel_id: 534184,
            },
            {
              id: '57767-220-530909',
              type: 'PP',
              category: 'Receiving Yards',
              name: 'Bryce Ford-Wheaton',
              teamAbbrev: 'WVU',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 76.5,
              over: -120,
              under: -120,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 530909,
              sel_id: 530909,
            },
            {
              id: '57767-24',
              type: 'GP',
              category: 'Team Total',
              name: 'West Virginia',
              teamAbbrev: 'WVU',
              offline: true,
              spread: null,
              spread_odd: null,
              total: 24.5,
              over: -115,
              under: -115,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'One',
              under_result: 'Zero',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: 1544,
              playerId: null,
              sel_id: 1544,
            },
            {
              id: '57767-24',
              type: 'GP',
              category: 'Team Total',
              name: 'Baylor',
              teamAbbrev: 'BAYLOR',
              offline: true,
              spread: null,
              spread_odd: null,
              total: 28.5,
              over: -115,
              under: -115,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'One',
              under_result: 'Zero',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: 1430,
              playerId: null,
              sel_id: 1430,
            },
            {
              id: '57767-12',
              type: 'GP',
              category: '1Q Game Line',
              name: 'West Virginia',
              teamAbbrev: 'WVU',
              offline: true,
              spread: 0.5,
              spread_odd: -140,
              total: 10.5,
              over: -115,
              under: -115,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'One',
              spread_stat: null,
              over_result: 'Zero',
              under_result: 'One',
              total_stat: null,
              moneyline_result: 'One',
              moneyline_stat: null,
              teamId: 1544,
              playerId: null,
              sel_id: 1544,
            },
            {
              id: '57767-8',
              type: 'GP',
              category: '1H Game Line',
              name: 'Baylor',
              teamAbbrev: 'BAYLOR',
              offline: true,
              spread: -1.5,
              spread_odd: -115,
              total: 27.5,
              over: -110,
              under: -110,
              moneyline: -145,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'One',
              spread_stat: null,
              over_result: 'One',
              under_result: 'Zero',
              total_stat: null,
              moneyline_result: 'One',
              moneyline_stat: null,
              teamId: 1430,
              playerId: null,
              sel_id: 1430,
            },
            {
              id: '57767-6',
              type: 'GM',
              category: 'Game Line',
              name: 'Baylor',
              teamAbbrev: 'BAYLOR',
              offline: true,
              spread: -3,
              spread_odd: -110,
              total: 55,
              over: -110,
              under: -110,
              moneyline: -160,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Zero',
              spread_stat: null,
              over_result: 'One',
              under_result: 'Zero',
              total_stat: null,
              moneyline_result: 'Zero',
              moneyline_stat: null,
              teamId: 1430,
              playerId: null,
              sel_id: 1430,
            },
            {
              id: '57767-12',
              type: 'GP',
              category: '1Q Game Line',
              name: 'Baylor',
              teamAbbrev: 'BAYLOR',
              offline: true,
              spread: -0.5,
              spread_odd: 110,
              total: 10.5,
              over: -115,
              under: -115,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Zero',
              spread_stat: null,
              over_result: 'Zero',
              under_result: 'One',
              total_stat: null,
              moneyline_result: 'Zero',
              moneyline_stat: null,
              teamId: 1430,
              playerId: null,
              sel_id: 1430,
            },
            {
              id: '57767-6',
              type: 'GM',
              category: 'Game Line',
              name: 'West Virginia',
              teamAbbrev: 'WVU',
              offline: true,
              spread: 3,
              spread_odd: -110,
              total: 55,
              over: -110,
              under: -110,
              moneyline: 140,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'One',
              spread_stat: null,
              over_result: 'One',
              under_result: 'Zero',
              total_stat: null,
              moneyline_result: 'One',
              moneyline_stat: null,
              teamId: 1544,
              playerId: null,
              sel_id: 1544,
            },
            {
              id: '57767-8',
              type: 'GP',
              category: '1H Game Line',
              name: 'West Virginia',
              teamAbbrev: 'WVU',
              offline: true,
              spread: 1.5,
              spread_odd: -105,
              total: 27.5,
              over: -110,
              under: -110,
              moneyline: 125,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Zero',
              spread_stat: null,
              over_result: 'One',
              under_result: 'Zero',
              total_stat: null,
              moneyline_result: 'Zero',
              moneyline_stat: null,
              teamId: 1544,
              playerId: null,
              sel_id: 1544,
            },
            {
              id: '57767-225-562565',
              type: 'PP',
              category: 'Rushing Yards',
              name: 'Richard Reese',
              teamAbbrev: 'BAYLOR',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 74.5,
              over: -120,
              under: -120,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 562565,
              sel_id: 562565,
            },
            {
              id: '57767-229',
              type: 'GP',
              category: 'Score First',
              name: 'West Virginia',
              teamAbbrev: 'WVU',
              offline: true,
              spread: null,
              spread_odd: null,
              total: 0.5,
              over: -110,
              under: -120,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'One',
              under_result: 'Zero',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: 1544,
              playerId: null,
              sel_id: 1544,
            },
            {
              id: '57767-220-538718',
              type: 'PP',
              category: 'Receiving Yards',
              name: 'Kaden Prather',
              teamAbbrev: 'WVU',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 58.5,
              over: -120,
              under: -120,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 538718,
              sel_id: 538718,
            },
            {
              id: '57767-236-534184',
              type: 'PP',
              category: 'TD Passes',
              name: 'JT Daniels',
              teamAbbrev: 'WVU',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 1.5,
              over: -125,
              under: -115,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 534184,
              sel_id: 534184,
            },
            {
              id: '57767-229',
              type: 'GP',
              category: 'Score First',
              name: 'Baylor',
              teamAbbrev: 'BAYLOR',
              offline: true,
              spread: null,
              spread_odd: null,
              total: 0.5,
              over: -120,
              under: -110,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Zero',
              under_result: 'One',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: 1430,
              playerId: null,
              sel_id: 1430,
            },
            {
              id: '57767-220-533742',
              type: 'PP',
              category: 'Receiving Yards',
              name: 'Ben Sims',
              teamAbbrev: 'BAYLOR',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 37.5,
              over: -115,
              under: -125,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 533742,
              sel_id: 533742,
            },
            {
              id: '57767-236-539394',
              type: 'PP',
              category: 'TD Passes',
              name: 'Blake Shapen',
              teamAbbrev: 'BAYLOR',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 1.5,
              over: -135,
              under: -105,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 539394,
              sel_id: 539394,
            },
            {
              id: '57767-220-530898',
              type: 'PP',
              category: 'Receiving Yards',
              name: 'Sam James',
              teamAbbrev: 'WVU',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 51.5,
              over: -120,
              under: -120,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              teamId: null,
              playerId: 530898,
              sel_id: 530898,
            },
          ],
        },
      },
    },
  });
}

main()
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
